import { GameAssetDefinition } from '../../models';

export const MARTIAL_ARTS_ASSETS: GameAssetDefinition[] = [
  {
    id: 'martial_arts.heavenquaker_spear',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-heavenquaker-spear.png',
    label: 'Heavenquaker Spear',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'spear'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.infernal_twinblades',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-infernal-twinblades.png',
    label: 'Infernal Twinblades',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'twinblades'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.inkwell_fan',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-inkwell-fan.png',
    label: 'Inkwell Fan',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'fan'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.mortal_rope_dart',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-mortal-rope-dart.png',
    label: 'Mortal Rope Dart',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'rope_dart'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.nameless_spear',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-nameless-spear.png',
    label: 'Nameless Spear',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'spear'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.nameless_sword',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-nameless-sword.png',
    label: 'Nameless Sword',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'sword'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.panacea_fan',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-panacea-fan.png',
    label: 'Panacea Fan',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'fan'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.soulshade_umbrella',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-soulshade-umbrella.png',
    label: 'Soulshade Umbrella',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'umbrella'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.stormbreaker_spear',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-stormbreaker-spear.png',
    label: 'Stormbreaker Spear',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'spear'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.strategic_sword',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-strategic-sword.png',
    label: 'Strategic Sword',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'sword'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.thundercry_blade',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-thundercry-blade.png',
    label: 'Thundercry Blade',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'blade'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
  {
    id: 'martial_arts.vernal_umbrella',
    category: 'martial_arts',
    file: 'assets/game/martial-arts/martial-arts-vernal-umbrella.png',
    label: 'Vernal Umbrella',
    kind: 'martial-art-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Martial Art selector banner used in the Martial Arts planner.',
    game_system_tags: ['martial_arts', 'planner', 'selector', 'umbrella'],
    ui_usage_notes: 'Use for toggle/select UI; pairs the in-game banner with the planner entry.',
    width: 1600,
    height: 400,
    aspect_ratio: '4:1',
  },
];
