import { GameAssetDefinition } from "../../models";

export const MYSTIC_SKILL_ASSETS: GameAssetDefinition[] = [
  {
    id: 'mystic_skill.blinding_mist',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-blinding-mist.png',
    label: 'Blinding Mist',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Releases a poisonous mist in front of you that blinds and briefly disables weaker enemies. Pairs with Touch of Death to finish targets caught in the cloud.',
    game_system_tags: ['special', 'assassin', 'cc', 'control'],
    ui_usage_notes:
      'Use when talking about stealth assassinations or Blinding Mist + Touch of Death combo setups in guides.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.divine_counter',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-divine-counter.png',
    label: 'Divine Counter',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Talent-tree counter skill that lets you answer a guarded attack with a precise kick, dealing damage and heavily slowing the target’s Endurance recovery.',
    game_system_tags: ['special', 'pvp', 'cc', 'control'],
    ui_usage_notes:
      'Use for PvP-focused counter-play tips or when explaining Talent-tree utility mystic skills.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.dragons_breath',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-dragons-breath.png',
    label: "Dragon's Breath",
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Enter an intoxicated stance, then breathe fire in front of you, dealing burst damage and stacking Ignition while granting damage reduction and fortitude.',
    game_system_tags: ['special', 'dps', 'hybrid'],
    ui_usage_notes:
      'Use when describing fire/Intoxicated-based mystic combos, especially paired with Drunken Poet.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.drunken_poet',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-drunken-poet.png',
    label: 'Drunken Poet',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Drink to enter an intoxicated state, then chain up to five flowing strikes that deal damage and apply Drunken Haze, with extra payoff when targets are ignited.',
    game_system_tags: ['special', 'dps', 'hybrid'],
    ui_usage_notes:
      'Use for “drunk fist” style builds or guides that explain Drunken Haze + Ignition synergies.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.flaming_meteor',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-flaming-meteor.png',
    label: 'Flaming Meteor',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Charge forward and leap skyward, hurling a flaming spear that explodes in an area before you crash down like a meteor for a second AoE hit, gaining strong damage reduction while casting.',
    game_system_tags: ['special', 'dps', 'aoe', 'hybrid'],
    ui_usage_notes:
      'Use when showcasing big, cinematic burst mystic skills or AoE-centric melee builds.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.free_morph',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-free-morph.png',
    label: 'Free Morph',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Vault into the air and unleash a flurry of midair kicks, juggling a single target and slamming them into the ground for area damage.',
    game_system_tags: ['special', 'dps', 'cc', 'control'],
    ui_usage_notes:
      'Use in combo guides that feature juggle-heavy playstyles or Skill Theft puzzler rewards.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.ghost_bind',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-ghost-bind.png',
    label: 'Ghost Bind',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'A control mystic art that pins humanoid targets in place like they are bound by invisible cords, leaving them helpless for follow-up attacks.',
    game_system_tags: ['special', 'cc', 'control'],
    ui_usage_notes:
      'Use when explaining crowd-control setups against human enemies or highlighting Forsaken Quarter quest rewards.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.glow_of_fireflies',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-glow-of-fireflies.png',
    label: 'Glow of Fireflies',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Summons a ring of fireflies that gently lights the surroundings for a short duration. A pure utility art with no combat effect.',
    game_system_tags: ['special', 'exploration'],
    ui_usage_notes:
      'Use for exploration/lighting tips, cave runs, or “quality of life” mystic skill recommendations.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.guardian_palm',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-guardian-palm.png',
    label: 'Guardian Palm',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Strike the ground with a heavy palm to deal AoE damage; when cast from height it turns into Lamp Light, a falling palm that knocks enemies back in a small area.',
    game_system_tags: ['special', 'dps', 'aoe'],
    ui_usage_notes:
      'Use when covering Ruins of the Thousand Buddhas rewards, or as a generic AoE mystic icon for melee builds.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.leaping_toad',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-leaping-toad.png',
    label: 'Leaping Toad',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Flip back to knock away enemies, then lunge forward to apply Toad Venom; a third cast becomes Golden Toad Crash, a powerful AoE slam that detonates the venom.',
    game_system_tags: ['special', 'dps', 'cc', 'control'],
    ui_usage_notes:
      'Use for guides about poison/Toad Venom setups, crowd-control packs, or General’s Shrine Skill Theft rewards.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.lions_roar',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-lions-roar.png',
    label: "Lion's Roar",
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Unleash a thunderous shout that damages and staggers enemies in front of you, also detonating Toad Venom from Leaping Toad for explosive follow-ups.',
    game_system_tags: ['special', 'dps', 'cc', 'control'],
    ui_usage_notes:
      'Use when highlighting Leaping Toad + Lion’s Roar synergy or showcasing kung-fu-movie inspired mystic builds.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.serene_breeze',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-serene-breeze.png',
    label: 'Serene Breeze',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Circulates Qi through your body to break control effects, letting you act even while pressured and briefly reducing enemy Endurance recovery on hit.',
    game_system_tags: ['special', 'defense', 'cc', 'control'],
    ui_usage_notes:
      'Use in survivability / anti-CC sections such as PvP tips, boss mechanics, or panic-button mystic layouts.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.soaring_spin',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-soaring-spin.png',
    label: 'Soaring Spin',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'A single-target control skill that pulls or lifts an enemy into the air with a spinning strike, leaving them exposed for follow-up combos.',
    game_system_tags: ['special', 'cc', 'control', 'dps'],
    ui_usage_notes:
      'Use in combo-route examples that juggle or reposition a priority target, especially Soaring Spin unlock walkthroughs.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.star_shift',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-star-shift.png',
    label: 'Star Shift',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Assist-deflection mystic art that consumes Insight to parry incoming attacks at the last moment, nullifying the blow when timed correctly.',
    game_system_tags: ['special', 'defense', 'pvp'],
    ui_usage_notes:
      'Use when explaining parry/deflection systems, Insight management, or assist-deflection settings.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.talon_strike',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-talon-strike.png',
    label: 'Talon Strike',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Dash at a target like a diving falcon, breaking their guard with the opening swipe, then follow with a short flurry of strikes that shred defenses.',
    game_system_tags: ['special', 'dps', 'assassin'],
    ui_usage_notes:
      'Use for early-game offensive mystic recommendations or any guide about breaking elite defenses quickly.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.touch_of_death',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-touch-of-death.png',
    label: 'Touch of Death',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Signature assassination art that lets you slip behind an unaware or weakened enemy and strike a vital point, often killing common foes outright.',
    game_system_tags: ['special', 'assassin'],
    ui_usage_notes:
      'Use for stealth/assassination walkthroughs, fort infiltration guides, and explanations of why Echoes of Old Battles is important.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.veil_of_stillness',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-veil-of-stillness.png',
    label: 'Veil of Stillness',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Suppresses your presence and steadies your breathing, making enemies much less likely to notice you until you directly engage in combat.',
    game_system_tags: ['special', 'assassin'],
    ui_usage_notes:
      'Use wherever you talk about stealth infiltration routes, Skill Theft requirements, or sneaking into sanctums.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.wind_sense',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-wind-sense.png',
    label: 'Wind Sense',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Reads disturbances in the air to highlight nearby enemies, interactables, and points of interest, acting as a scouting / awareness tool.',
    game_system_tags: ['special', 'exploration', 'guide'],
    ui_usage_notes:
      'Use for exploration tips, “how to find things on the map” sections, or Talent-page utility mystic callouts.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.wolflike_frenzy',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-wolflike-frenzy.png',
    label: 'Wolflike Frenzy',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Channel power into your staff to knock a foe down, hammer them with rapid blows, then launch them upward; especially effective against cavalry and unstable targets.',
    game_system_tags: ['special', 'dps', 'cc', 'control'],
    ui_usage_notes:
      'Use in staff-focused build writeups or any guide that highlights anti-cavalry tools and long knockdown chains.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.yaksha_rush',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-yaksha-rush.png',
    label: 'Yaksha Rush',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'A late-Qinghe offensive mystic art rewarded from The Promised Light legacy, used as an aggressive gap-closer and burst tool against tougher enemies.',
    game_system_tags: ['special', 'dps'],
    ui_usage_notes:
      'Use when marking endgame Jianghu Legacy rewards or showcasing high-impact offensive mystic skills for advanced builds.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.thousand_mile_flight',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-thousand-mile-flight.png',
    label: 'Thousand-Mile Flight',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Movement / lightness Mystic Skill that lets you soar across the sky in long-distance flight once regional lightness permissions are unlocked.',
    game_system_tags: ['special', 'movement', 'lightness_skill', 'flight', 'exploration'],
    ui_usage_notes:
      'Use anywhere you explain flying / long-range lightness movement, A Warrior’s Journey rewards, or guides that assume Thousand-Mile Flight is unlocked.',
    width: 760,
    height: 720,
    aspect_ratio: '19:18',
  },
  {
    id: 'mystic_skill.golden_body',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-golden-body.png',
    label: 'Golden Body',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Support Mystic Skill that grants an 8-second Golden Body shield with Qi recovery; while the shield holds you gain Fortitude and significant damage reduction.',
    game_system_tags: ['special', 'support', 'defense', 'shield'],
    ui_usage_notes:
      'Use on defensive-mystic-skill sections, mitigation checklists, or when highlighting popular “oh-shit button” survivability options.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.tai_chi',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-tai-chi.png',
    label: 'Tai Chi',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Puzzle / control Mystic Skill that gathers leaves or stirs the water outside combat, and in combat pulls, whirls, then hurls enemies; especially strong at breaking shielded targets.',
    game_system_tags: ['special', 'cc', 'control'],
    ui_usage_notes:
      'Use when describing shield-breaking tools, Tai Chi puzzle interactions, or CC-focused mystic-skill rotations.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.dragon_head',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-dragon-head.png',
    label: 'Dragon Head',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'High-cooldown burst Mystic Skill that shapes dust and leaves into a dragon’s head, dealing heavy damage in front and knocking enemies back while granting damage reduction and Super Armor.',
    game_system_tags: ['special', 'dps'],
    ui_usage_notes:
      'Use in burst-DPS or showcase build sections when you want to highlight “ultimate-style” mystic skills.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.celestial_seize',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-celestial-seize.png',
    label: 'Celestial Seize',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Puzzle / utility Mystic Skill that pulls distant objects, including items in chests or on NPCs, and in combat can disarm enemies and strike them with their own weapon for Qi damage.',
    game_system_tags: ['special', 'cc', 'control', 'exploration'],
    ui_usage_notes:
      'Use in exploration guides, “how to steal / grab items at range” tips, or CC utility breakdowns.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.cloud_steps',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-cloud-steps.png',
    label: 'Cloud Steps',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Puzzle lightness Mystic Skill that lets you leap high and slam down or jump to marked spots; in combat you stomp on an enemy’s shoulders, especially effective versus cavalry or unstable targets.',
    game_system_tags: ['special', 'movement', 'lightness_skill', 'exploration'],
    ui_usage_notes:
      'Use wherever a guide calls out Cloud Steps jump routes, high ledges, or anti-cavalry tech.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.meridian_touch',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-meridian-touch.png',
    label: 'Meridian Touch',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Acupoint-strike Mystic Skill that can immobilize enemies and break Vital Spots, boosting Weak Point Break damage and later Qi damage taken.',
    game_system_tags: ['special', 'cc', 'control'],
    ui_usage_notes:
      'Use in Weak Point / acupoint guides and when explaining how to set up burst windows with mystic skills.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.still_waters',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-still-waters.png',
    label: 'Still Waters',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General enhancement Mystic Skill that, while you hold your breath, drastically slows nearby enemies’ movement speed at the cost of steadily draining Endurance.',
    game_system_tags: ['special', 'cc', 'control', 'slow'],
    ui_usage_notes:
      'Use when talking about crowd control or breath-hold tech, especially in PvP/duel tips.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.skywalk_dash',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-skywalk-dash.png',
    label: 'Skywalk Dash',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Core lightness Mystic Skill that lets you perform a quick dash while on the ground or in midair, consuming Vitality instead of stamina.',
    game_system_tags: ['special', 'movement', 'dash', 'lightness_skill'],
    ui_usage_notes:
      'Use whenever you explain basic movement tech (dash cancels, repositioning, midair dodges).',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.threefold_skywalk',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-threefold-skywalk.png',
    label: 'Threefold Skywalk',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Lightness Mystic Skill that allows up to three consecutive jumps, forming the backbone of most advanced air movement and combos.',
    game_system_tags: ['special', 'movement', 'lightness_skill'],
    ui_usage_notes:
      'Use as the default icon for triple-jump requirements, vertical platforming, or aerial combo routes.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.ghostly_steps',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-ghostly-steps.png',
    label: 'Ghostly Steps',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Support Mystic Skill that grants Mirage status, reducing Endurance cost of dodge skills and slightly extending untargetable frames for a duration.',
    game_system_tags: ['special', 'support', 'movement'],
    ui_usage_notes:
      'Use in survivability / dodge-tech writeups, especially for players learning i-frames and Mirage windows.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.wind_rider',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-wind-rider.png',
    label: 'Wind Rider',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Movement / lightness Mystic Skill that lets you ride the wind in long glides, acting as one of the core “flying” lightness options once unlocked through exploration.',
    game_system_tags: ['special', 'movement', 'lightness_skill', 'flight', 'exploration'],
    ui_usage_notes:
      'Use for regional flying / glide routing guides and any explanation of the Wind Rider lightness path.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.meteor_flight',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-meteor-flight.png',
    label: 'Meteor Flight',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Spear-flavored lightness Mystic Skill that propels you like a shooting star, functioning as a movement / flying option tied to exploration unlocks.',
    game_system_tags: ['special', 'movement', 'lightness_skill', 'flight', 'exploration'],
    ui_usage_notes:
      'Use when mapping out Meteor Flight unlocks, long glides over water, or stylish travel routes.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.fan_glider',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-fan-glider.png',
    label: 'Fan Glider',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Movement lightness Mystic Skill that lets you glide through the air with a fan; unlocked via high Qinghe exploration and used purely for traversal.',
    game_system_tags: ['special', 'movement', 'lightness_skill', 'flight', 'exploration'],
    ui_usage_notes:
      'Use for Qinghe exploration / fan-glide paths and when explaining alternate flying styles.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.honking_havoc',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-honking-havoc.png',
    label: 'Honking Havoc',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Support Mystic Skill that forces a goose to honk forward, dealing AoE damage and inflicting a long breath-hold effect on enemies.',
    game_system_tags: ['special', 'support', 'aoe', 'cc'],
    ui_usage_notes:
      'Use in oddity / meme build sections or when highlighting breath-hold CC tools.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.abyss_dive',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-abyss-dive.png',
    label: 'Abyss Dive',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Exploration Mystic Skill that unlocks deep-water diving and underwater swimming, enabling access to submerged chests and oddities.',
    game_system_tags: ['special', 'movement', 'dive', 'exploration'],
    ui_usage_notes:
      'Use whenever guides send players underwater or talk about hidden content reachable only by diving.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.safe_mighty_drop',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-safe-mighty-drop.png',
    label: 'Safe Mighty Drop',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Upgrade to Mighty Drop that, after mastering Silent Fall, lets your landing become immune to Disease and fall damage when you slam down.',
    game_system_tags: ['special', 'movement', 'lightness_skill'],
    ui_usage_notes:
      'Use when explaining high-altitude routes, safe ground slams, or cliff-diving shortcuts.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.wallstride_shadowdash',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-wallstride-shadowdash.png',
    label: 'Wallstride – Shadowdash',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Movement lightness Mystic Skill that lets you sprint along walls and cliffs in a darker, “shadow dash” style, chaining with other lightness moves for complex routes.',
    game_system_tags: ['special', 'movement', 'wall_run', 'lightness_skill', 'exploration'],
    ui_usage_notes:
      'Use for wall-running path diagrams, city-parkour routes, or any explanation of Wallstride unlock chains.',
    width: 880,
    height: 720,
    aspect_ratio: '11:9',
  },
  {
    id: 'mystic_skill.mighty_drop',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-mighty-drop.png',
    label: 'Mighty Drop',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Movement lightness Mystic Skill that lets you cancel Threefold Skywalk with a rapid plunge, slamming toward the ground after a high jump.',
    game_system_tags: ['special', 'movement', 'lightness_skill'],
    ui_usage_notes:
      'Use when teaching aerial routes, fast descents from height, or setups that chain into Safe Mighty Drop.',
    width: 720,
    height: 720,
    aspect_ratio: '1:1',
  },
  {
    id: 'mystic_skill.wallstride_swiftstride',
    category: 'mystic_skill',
    file: 'assets/game/mystic-skill/mystic-skill-wallstride-swiftstride.png',
    label: 'Wallstride – Swiftstride',
    kind: 'mystic-skill-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Graceful wall-running lightness Mystic Skill that lets you dash along walls and eaves at speed, forming a smoother traversal option than Shadowdash.',
    game_system_tags: ['special', 'movement', 'wall_run', 'lightness_skill', 'exploration'],
    ui_usage_notes:
      'Use in any guide that relies on wall-running (city roofs, cliff routes, or vertical dungeons) and wants to distinguish the Swiftstride variant.',
    width: 840,
    height: 720,
    aspect_ratio: '7:6',
  },
];
