import { GameAssetDefinition } from '../../models';

export const GEAR_ENHANCE_ASSETS: GameAssetDefinition[] = [
  {
    id: 'gear_enhance.armor',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-armor.png',
    label: 'Armor',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.bracer',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-bracer.png',
    label: 'Bracer',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.disc',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-disc.png',
    label: 'Disc',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.greaves',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-greaves.png',
    label: 'Greaves',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.helm',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-helm.png',
    label: 'Helm',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.left_hand_weapon',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-left-hand-weapon.png',
    label: 'Left-hand Weapon',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.pendant',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-pendant.png',
    label: 'Pendant',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
  {
    id: 'gear_enhance.right_hand_weapon',
    category: 'gear_enhance',
    file: 'assets/game/gear-enhance/gear-enhance-right-hand-weapon.png',
    label: 'Right-hand Weapon',
    kind: 'gear-enhance-slot-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gear Enhancement slot icon used as a selector in the Gear Enhancement planner.',
    game_system_tags: ['gear_enhance', 'planner', 'slot'],
    ui_usage_notes:
      'Use for slot selection (8-slot grid); helps players recognize each gear piece.',
    width: 240,
    height: 240,
    aspect_ratio: '1:1',
  },
];
