import { GameAssetDefinition } from "../../models";

export const INNER_WAY_ASSETS: GameAssetDefinition[] = [
  {
    id: 'inner_way.sword_morph',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-sword-morph.png',
    label: 'Sword Morph',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Splendor Inner Way that upgrades Nameless Sword’s Charged Skill Vagrant Sword, firing extra sword energy when charged with a Qi shield and allowing you to spend extra Endurance to boost its damage.',
    game_system_tags: [
      'inner_way',
      'bellstrike_splendor',
      'attack',
      'martial_arts',
      'damage_boost',
    ],
    ui_usage_notes:
      'Use on guides or builds focused on Nameless Sword charged attacks and Bellstrike – Splendor burst setups.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.battle_anthem',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-battle-anthem.png',
    label: 'Battle Anthem',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Splendor Inner Way that increases damage dealt by Charged Skills against bosses, improving sustained boss DPS for melee builds.',
    game_system_tags: ['inner_way', 'bellstrike_splendor', 'attack', 'damage_boost', 'boss'],
    ui_usage_notes:
      'Use when highlighting boss-focused Bellstrike – Splendor builds or Inner Way recommendations for melee DPS.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.adaptive_steel',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-adaptive-steel.png',
    label: 'Adaptive Steel',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Umbra Inner Way that grants a special Martial Skill depending on the equipped blade weapon; sword and dual blades each gain their own timed Martial Skill with separate cooldowns.',
    game_system_tags: ['inner_way', 'bellstrike_umbra', 'attack', 'support', 'buff'],
    ui_usage_notes:
      'Use for explanations of Adaptive Steel oddity unlocks and as a callout for bleed/umbra sword builds that swap blades.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.morale_chant',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-morale-chant.png',
    label: 'Morale Chant',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Legendary General Inner Way that grants stacks of Yi River when attacking or healing, increasing Physical Damage and healing for a duration, with stacks building over time.',
    game_system_tags: ['inner_way', 'general', 'attack', 'buff', 'stacking'],
    ui_usage_notes:
      'Use wherever you explain universal DPS / healer Inner Ways or Echo Jade investment into Morale Chant pages and notes.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.echoes_of_oblivion',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-echoes-of-oblivion.png',
    label: 'Echoes of Oblivion',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bamboocut – Wind Legendary Inner Way for Infernal Twinblades that applies Sin and Karma on light attacks; striking enemies marked with both debuffs lets your attacks ignore a portion of their defenses.',
    game_system_tags: ['inner_way', 'bamboocut_wind', 'attack', 'debuff', 'defense_shred'],
    ui_usage_notes:
      'Use on high-end Bamboocut Twinblade guides that talk about Sin/Karma management and armor-shred combos.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.evasive_charge',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-evasive-charge.png',
    label: 'Evasive Charge',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that gives a chance to refund all Endurance spent after a Perfect Dodge, rewarding precise evasions with more stamina for follow-up attacks.',
    game_system_tags: ['inner_way', 'general', 'cost_reduction', 'recover', 'dodge', 'endurance'],
    ui_usage_notes:
      'Use in survivability / dodge-tech sections or beginner Inner Way recommendations that emphasize learning Perfect Dodges.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.envigorated_warrior',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-envigorated-warrior.png',
    label: 'Envigorated Warrior',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that passively increases all damage and healing done, but disables the buff briefly after being hit and applies a Cage debuff that increases damage taken.',
    game_system_tags: ['inner_way', 'general', 'attack', 'buff', 'damage_boost', 'risk_reward'],
    ui_usage_notes:
      'Use when discussing glass-cannon style Inner Way setups or Still Shore quest rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.bitter_seasons',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-bitter-seasons.png',
    label: 'Bitter Seasons',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that adds a chance for your attacks to inflict a Poison DoT which also stacks a Physical Defense reduction on the target up to several layers.',
    game_system_tags: ['inner_way', 'general', 'attack', 'debuff', 'poison', 'stacking'],
    ui_usage_notes:
      'Use for DoT / debuff-oriented builds or when explaining Gleaming Abyss rewards and Mist Gate exploration.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.divine_roulette',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-divine-roulette.png',
    label: 'Divine Roulette',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that, after a successful deflect, grants one of several buffs that empower your next skill within a short window; can only trigger periodically.',
    game_system_tags: ['inner_way', 'general', 'counter', 'buff', 'damage_boost', 'deflect'],
    ui_usage_notes:
      'Use in parry/deflect tech sections or Gleaming Abyss Inner Way callouts where you highlight reactive playstyles.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.fury_harvest',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-fury-harvest.png',
    label: 'Fury Harvest',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way for Mystic Arts that gives certain recovery actions a chance to grant extra Vitality, increasing how often you can cast Mystic Arts without relying on attacks or parries.',
    game_system_tags: ['inner_way', 'general', 'support', 'mystic_arts', 'vitality', 'recover'],
    ui_usage_notes:
      'Use when talking about Mystic Art uptime, Vitality management, or the Lost Chapter questline in Bodhi Sea.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.vital_leech',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-vital-leech.png',
    label: 'Vital Leech',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that lets Exhaustion Execution skills restore a portion of HP based on the damage dealt, turning executions into strong self-heals.',
    game_system_tags: ['inner_way', 'general', 'pursuit', 'recover', 'execution'],
    ui_usage_notes:
      'Use for melee sustain build guides or notes about Palace of Annals Lost Chapter rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.restoring_blossom',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-restoring-blossom.png',
    label: 'Restoring Blossom',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Deluge Inner Way that makes critical heals apply Nurturing stacks, increasing healing received for a short time and stacking several times.',
    game_system_tags: ['inner_way', 'silkbind_deluge', 'support', 'heal', 'stacking'],
    ui_usage_notes:
      'Use on healer build write-ups, especially when covering Healer’s Union unlock steps and crit-healing synergies.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.royal_remedy',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-royal-remedy.png',
    label: 'Royal Remedy',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Deluge Inner Way for Panacea Fan that boosts the healing from Cloudburst Healing’s water clone and generates Dewdrops for allies healed within its area.',
    game_system_tags: ['inner_way', 'silkbind_deluge', 'support', 'heal', 'dewdrop'],
    ui_usage_notes:
      'Use in Panacea Fan healer guides or Inner Way overviews explaining Dewdrop-based sustain tools.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.blossom_barrage',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-blossom-barrage.png',
    label: 'Blossom Barrage',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Jade Legendary Inner Way that gives Vernal Umbrella’s Spring Sorrow extra charges and applies a debuff making enemies take increased damage from specific ballistic skills.',
    game_system_tags: ['inner_way', 'silkbind_jade', 'attack', 'martial_arts', 'damage_boost'],
    ui_usage_notes:
      'Use for ranged control/DPS Vernal Umbrella builds or when describing Shadows in Bloom quest rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.thunderous_bloom',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-thunderous-bloom.png',
    label: 'Thunderous Bloom',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Jade Inner Way that rewards moving a set distance quickly by granting Spring Thunder, buffing the damage of your next few Heavy or Airborne Heavy Attacks.',
    game_system_tags: ['inner_way', 'silkbind_jade', 'damage_boost', 'buff', 'movement'],
    ui_usage_notes:
      'Use in mobile ranged build sections or Mercyheart Monastery outpost reward callouts.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.seasonal_edge',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-seasonal-edge.png',
    label: 'Seasonal Edge',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that grants one of several offensive buffs after casting a dual-weapon skill, giving flexible damage bonuses for dual-wield setups.',
    game_system_tags: ['inner_way', 'general', 'attack', 'buff', 'damage_boost', 'dual_weapon'],
    ui_usage_notes:
      'Use when covering Kaifeng Fairgrounds calligraphy shop purchases or dual-weapon Inner Way synergies.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.insightful_strike',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-insightful-strike.png',
    label: 'Insightful Strike',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Umbra Inner Way where dealing Affinity damage builds Focus; at max Focus you enter Concentration, boosting Affinity damage and occasionally reducing damage taken.',
    game_system_tags: ['inner_way', 'bellstrike_umbra', 'attack', 'damage_boost', 'defense'],
    ui_usage_notes:
      'Use for Strategic Sword bleed/affinity builds or when explaining Feng Jisheng’s archery challenge rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.sword_horizon',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-sword-horizon.png',
    label: 'Sword Horizon',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Umbra Legendary Inner Way for Strategic Sword that adds a timing-based follow-up attack after Martial, Special, or Charged Skills; consuming Bleed stacks for a large burst when fully stacked.',
    game_system_tags: [
      'inner_way',
      'bellstrike_umbra',
      'attack',
      'martial_arts',
      'pursuit',
      'bleed',
    ],
    ui_usage_notes:
      'Use when highlighting high-skill Bellstrike combos or Ghostlight Market Unknown Old Book farming routes.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.exquisite_scenery',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-exquisite-scenery.png',
    label: 'Exquisite Scenery',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Stonesplit – Might Inner Way that turns successful Thundercry Blade blocks into a special counter, letting you instantly fire a first-stage charged heavy and restoring Battle Will when you land varied combos.',
    game_system_tags: ['inner_way', 'stonesplit_might', 'defense', 'martial_arts', 'counter'],
    ui_usage_notes:
      'Use in tank build write-ups focused on Thundercry Blade counterplay and Northern Vow Ruins monk encounter rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.flying_gourds',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-flying-gourds.png',
    label: 'Flying Gourds',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Silkbind – Jade Inner Way that adds a second charge to Inkwell Fan's Martial Arts Skill Peak's Springless Silence at the cost of a slightly longer cooldown.",
    game_system_tags: ['inner_way', 'path', 'martial', 'ranged', 'support'],
    ui_usage_notes:
      'Use when describing Silkbind – Jade builds that double up on Springless Silence casts or discuss fan/umbrella control-support setups.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.mountains_might',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-mountains-might.png',
    label: "Mountain's Might",
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Bellstrike – Splendor Inner Way that lets Noname Spear's Qiankun's Lock grant the Endless Gale effect, increasing its Endurance cost reduction window for a short time.",
    game_system_tags: ['inner_way', 'path', 'martial', 'melee', 'support'],
    ui_usage_notes:
      'Use in Bellstrike – Splendor spear build notes, especially when talking about Endurance-saving loops and Qiankun’s Lock optimization.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.riptide_reflex',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-riptide-reflex.png',
    label: 'Riptide Reflex',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bamboocut – Wind Inner Way that briefly reduces the cooldown of your current Martial Arts Skill whenever you land a hit with a qualifying control skill, with an internal cooldown.',
    game_system_tags: ['inner_way', 'path', 'martial', 'assassin', 'melee', 'control', 'cc'],
    ui_usage_notes:
      'Use in assassin/Infernal Twinblades path guides when highlighting control-skill chains and Martial Arts uptime improvements.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.fivefold_bleed',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-fivefold-bleed.png',
    label: 'Fivefold Bleed',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that lets attacks occasionally apply Weeping Blood stacks which deal periodic damage; at five stacks the effect detonates for a single strong hit.',
    game_system_tags: ['inner_way', 'bleed', 'dps'],
    ui_usage_notes:
      'Use wherever you talk about bleed-centric builds, bleed detonations, or generic DPS Inner Ways that work across multiple paths.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.shadow_assault',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-shadow-assault.png',
    label: 'Shadow Assault',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way focused on assassin Mystic Arts, extending the ambush range of Touch of Death so you can open from farther away.',
    game_system_tags: ['inner_way', 'assassin', 'dps'],
    ui_usage_notes:
      'Use when covering stealth/assassin Mystic Art setups or long-range ambush openers in build guides.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.wildfire_spark',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-wildfire-spark.png',
    label: 'Wildfire Spark',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Splendor Inner Way that refunds a small percentage of Endurance whenever you spend it, turning heavy Endurance use into extra sustain.',
    game_system_tags: ['inner_way', 'path', 'martial', 'melee', 'support'],
    ui_usage_notes:
      'Use on Bellstrike Splendor guides that emphasize Endurance-hungry combos or QoL sustain for repeated charged skills and dodges.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.star_reacher',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-star-reacher.png',
    label: 'Star Reacher',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Jade Inner Way that grants a short Physical Attack bonus after you knock an enemy airborne, rewarding frequent juggles.',
    game_system_tags: ['inner_way', 'path', 'martial', 'ranged', 'dps'],
    ui_usage_notes:
      'Use in ranged umbrella/fan build notes that revolve around launching targets and capitalizing on airborne windows.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.mending_loom',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-mending-loom.png',
    label: 'Mending Loom',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Silkbind – Deluge Inner Way that enhances Soulshade Umbrella's Special Skill Echoing Grow, restoring Dewdrops and providing extra healing based on Dewdrops spent.",
    game_system_tags: ['inner_way', 'path', 'healer', 'support', 'ranged'],
    ui_usage_notes:
      'Use for healer-focused guides where Dewdrop economy and burst healing from Echoing Grow are important talking points.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.evening_snow',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-evening-snow.png',
    label: 'Evening Snow',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General defensive Inner Way that, early in combat, automatically grants a short self-heal-over-time if your HP drops under a threshold, with a long cooldown.',
    game_system_tags: ['inner_way', 'support', 'healer', 'defense'],
    ui_usage_notes:
      'Use when explaining safety nets for new players, solo-survivability picks, or “panic button” passives in general Inner Way recommendations.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.trapped_beast',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-trapped-beast.png',
    label: 'Trapped Beast',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Stonesplit – Might Inner Way that, when you are very low on HP, creates a large temporary shield once in a long while, helping tanks survive lethal bursts.',
    game_system_tags: ['inner_way', 'path', 'tank', 'defense', 'melee'],
    ui_usage_notes:
      'Use for tank / Stonesplit Might writeups that highlight emergency shielding or last-stand mechanics.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.esoteric_revival',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-esoteric-revival.png',
    label: 'Esoteric Revival',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Silkbind – Deluge Inner Way that boosts the healing of Panacea Fan's Resurrection Perception Skill on revived allies, making its revive much stronger.",
    game_system_tags: ['inner_way', 'path', 'healer', 'support', 'ranged'],
    ui_usage_notes:
      'Use in co-op healer guides when emphasizing strong combat revives or clutch recovery tools.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.breaking_point',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-breaking-point.png',
    label: 'Breaking Point',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bamboocut – Wind Inner Way that adds Disintegration stacks when you crit Exhausted enemies, granting Physical Penetration and extra Critical Damage up to a small cap.',
    game_system_tags: ['inner_way', 'path', 'martial', 'assassin', 'melee', 'dps'],
    ui_usage_notes:
      'Use on high-crit assassin build sections that talk about shredding defenses and scaling crit damage against staggered targets.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.vendetta',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-vendetta.png',
    label: 'Vendetta',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Bamboocut – Wind Inner Way that extends Guided Blade's Vendetta Token duration and refunds Token of Gratitudes, smoothing out resource flow.",
    game_system_tags: ['inner_way', 'path', 'martial', 'assassin', 'melee', 'support'],
    ui_usage_notes:
      'Use where you cover Guided Blade/Bamboocut token management, especially for longer boss fights and resource sustain.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.steadfast_stance',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-steadfast-stance.png',
    label: 'Steadfast Stance',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General defensive Inner Way that reduces the chance of being staggered by most enemy hits (excluding bosses and players).',
    game_system_tags: ['inner_way', 'defense', 'tank'],
    ui_usage_notes:
      'Use when suggesting generic anti-flinch tech for PvE builds, especially for players who dislike being interrupted by trash mobs.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.wind_beneath_wings',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-wind-beneath-wings.png',
    label: 'Wind Beneath Wings',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General mobility Inner Way that lowers Skywalk Dash Endurance cost while jumping, briefly boosts move speed after landing, and heals a bit of HP whenever you defeat an enemy.',
    game_system_tags: ['inner_way', 'support', 'defense'],
    ui_usage_notes:
      'Use for movement-focused or exploration builds where cheaper dashes, speed bursts, and incidental healing matter.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.wolfchasers_art',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-wolfchasers-art.png',
    label: "Wolfchaser's Art",
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Bellstrike – Umbra Inner Way that lowers the combo requirement for Heavenquaker Spear's Sorrow Without Wine buff and can rapidly build combo count when hitting bleeding bosses.",
    game_system_tags: ['inner_way', 'path', 'martial', 'melee', 'bleed', 'dps'],
    ui_usage_notes:
      'Use for spear/Bellstrike Umbra bleed builds where Sorrow Without Wine uptime and boss-focused combos are key.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.art_of_resistance',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-art-of-resistance.png',
    label: 'Art of Resistance',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Stonesplit – Might Inner Way that lengthens the duration of your HP shields and their attached bonus effects, making shield-based skills last longer.',
    game_system_tags: ['inner_way', 'path', 'tank', 'defense'],
    ui_usage_notes:
      'Use in tank guides that emphasize shielding tools, prolonged mitigation, or shield-synergy Stonesplit builds.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.rock_solid',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-rock-solid.png',
    label: 'Rock Solid',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Stonesplit – Might Inner Way that boosts Roar of Storm's damage reduction after you taunt, stacking higher against bosses but slightly lowering your own damage while the reduction is active.",
    game_system_tags: ['inner_way', 'path', 'tank', 'defense'],
    ui_usage_notes:
      'Use when showcasing classic front-line Stonesplit tanks who trade personal damage for big damage reduction and aggro tools.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
];
