import { GameAssetDefinition } from '../../models/game-assets.model';

export const GAME_ASSETS: GameAssetDefinition[] = [
  {
    id: 'currency.adventure_slip',
    category: 'currency',
    file: 'assets/game/currency/currency-adventure-slip.png',
    label: 'Adventure Slip',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Co-op and online multiplayer currency (also called Four Seas Letters) used in the Four Seas / Wandering Paths style shops for cosmetics and housing-style rewards. Earned from Wandering Paths runs, co-op bounties, and other online activities; has a weekly cap.',
    game_system_tags: ['currency', 'coop', 'social', 'cosmetics', 'weekly_cap', 'wandering_paths'],
    ui_usage_notes:
      'Use whenever referencing co-op / Wandering Paths rewards, Four Seas shop cosmetics, or weekly multiplayer checklists.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.coin',
    category: 'currency',
    file: 'assets/game/currency/currency-coin.png',
    label: 'Coin',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Generic in-game money (Zhou Coin and regional variants) used for most merchant purchases, fees, and basic services. Lives in the Money Bag tab.',
    game_system_tags: ['currency', 'basic', 'merchant', 'economy'],
    ui_usage_notes:
      'Use as the default money icon for generic costs, vendor purchases, repairs, or other non-premium spending.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.commerce_coin',
    category: 'currency',
    file: 'assets/game/currency/currency-commerce-coin.png',
    label: 'Commerce Coin',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Mini-game and street-vendor currency used for wagers in activities like Pitch Pot, cards, Mahjong, and for buying street food. Also used for buying trade goods and items from commerce coin shop.',
    game_system_tags: ['currency', 'commerce', 'minigame', 'food'],
    ui_usage_notes:
      'Use when a guide or timer refers specifically to mini-game wagers or street food purchases instead of general merchants.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.echo_bead',
    category: 'currency',
    file: 'assets/game/currency/currency-echo-bead.png',
    label: 'Echo Bead',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Top-tier premium currency bought with real money. Used for Celestial Echo pulls and to purchase cash-shop bundles, cosmetics, and other high-end items.',
    game_system_tags: ['currency', 'premium', 'cash_shop', 'gacha'],
    ui_usage_notes:
      'Use for anything that clearly spends real-money premium currency; do not use for free-to-play only paths.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.echo_jade',
    category: 'currency',
    file: 'assets/game/currency/currency-echo-jade.png',
    label: 'Echo Jade',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'High-value earnable premium-like currency used at special merchants and systems, especially the Activity shop. Commonly spent on Internal Arts, power-progression items, cosmetics, and gacha tickets such as Lingering and Resonating Melodies.',
    game_system_tags: ['currency', 'premium_like', 'inner_way', 'gacha', 'economy'],
    ui_usage_notes:
      'Use when describing where to spend Echo Jade efficiently (Internal Arts, Activity shop, gacha tickets, etc.) or when labelling Echo Jade sinks in checklists.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.essence_of_earth',
    category: 'currency',
    file: 'assets/game/currency/currency-essence-of-earth.png',
    label: 'Essence of Earth',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Draw-shop token obtained from Solemn Echo (standard/free) gacha pulls. Spent in the Draw Shop on rewards associated with the Solemn Echo banner.',
    game_system_tags: ['currency', 'gacha', 'draw_shop', 'solemn_echo'],
    ui_usage_notes:
      'Use when a reward comes specifically from the Solemn Echo pool and is purchased via the draw-shop exchange.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.essence_of_heaven',
    category: 'currency',
    file: 'assets/game/currency/currency-essence-of-heaven.png',
    label: 'Essence of Heaven',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Draw-shop token obtained from Celestial Echo (premium) gacha pulls. Used to purchase rewards in the Draw Shop and can be converted towards Harmonic Cores.',
    game_system_tags: ['currency', 'gacha', 'draw_shop', 'celestial_echo', 'premium'],
    ui_usage_notes:
      'Use on guides that talk about Celestial Echo pity, draw-shop exchanges, or Harmonic Core conversion paths.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.fourfold_coin',
    category: 'currency',
    file: 'assets/game/currency/currency-fourfold-coin.png',
    label: 'Fourfold Coin',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bounty-shop currency earned from NPC and player bounties. Has a weekly cap and is spent in the Bounty Shop on cosmetics, materials, and some account progression.',
    game_system_tags: ['currency', 'bounties', 'coop', 'cosmetics', 'weekly_cap'],
    ui_usage_notes:
      'Use on bounty-related checklist items or when explaining what to buy from the Bounty Shop each week.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.harmonic_core',
    category: 'currency',
    file: 'assets/game/currency/currency-harmonic-core.png',
    label: 'Harmonic Core',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Legendary-tier draw currency from Celestial Echo pulls. Used in the Draw Shop for top-end cosmetics, visual effects, and other rare items. Can be exchanged into Sound Jade.',
    game_system_tags: ['currency', 'gacha', 'draw_shop', 'premium', 'legendary'],
    ui_usage_notes:
      'Use when explaining long-term premium progression, legendary skill effects, or apex draw-shop purchases.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.harmony_charm',
    category: 'currency',
    file: 'assets/game/currency/currency-harmony-charm.png',
    label: 'Harmony Charm',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Social / co-op currency (also called Private Funds of the Ward) with a weekly cap. Earned from co-op play, online mode, partnerships, and NPC quiz-style activities; spent in Brotherhood / Social shops on cosmetics and housing items.',
    game_system_tags: ['currency', 'coop', 'social', 'cosmetics', 'housing', 'weekly_cap'],
    ui_usage_notes:
      'Use on guides about partnerships, Brotherhood cosmetics, and co-op fashion or housing progression.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.jade_fish',
    category: 'currency',
    file: 'assets/game/currency/currency-jade-fish.png',
    label: 'Jade Fish',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Universal activity currency with a high weekly cap, earned from exploration, quests, enemies, chests, and activities. Spent in the Activity shop on Internal Arts, gear, and cosmetics.',
    game_system_tags: ['currency', 'activity', 'season_shop', 'weekly_cap'],
    ui_usage_notes:
      'Use for sections about Activity shop priorities, weekly caps, and general “play anything” income.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.sin_leaf',
    category: 'currency',
    file: 'assets/game/currency/currency-sin-leaf.png',
    label: 'Sin Leaf',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Special currency obtained in places like Perception Forest and used in the Sin Leaf Exchange for certain free-to-play cosmetics and accessories (for example the Yaksha outfit set and some accessories).',
    game_system_tags: ['currency', 'cosmetics', 'exploration', 'sin_leaf_exchange'],
    ui_usage_notes:
      'Use when a cosmetic specifically lists the Sin Leaf Exchange as its source; separates it from Jade or draw-based unlocks.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.sound_jade',
    category: 'currency',
    file: 'assets/game/currency/currency-sound-jade.png',
    label: 'Sound Jade',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'High-end draw-shop currency primarily obtained by exchanging Harmonic Cores (for example 1 Core → 5 Sound Jade). Used to buy legendary skill visual effects and other premium cosmetics in the Draw Shop.',
    game_system_tags: ['currency', 'gacha', 'draw_shop', 'premium'],
    ui_usage_notes:
      'Use on advanced guides about legendary skill VFX, Mirage Boat / event items tied to the Draw Shop, and other endgame cosmetic optimizations.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.treasure_token',
    category: 'currency',
    file: 'assets/game/currency/currency-treasure-token.png',
    label: 'Treasure Token',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Guild currency obtained from Guild Events and capped weekly. Used in the Red Gold Boutique / guild shop to buy cosmetics, Mahjong chip bags, fireworks, and other guild-flavored items.',
    game_system_tags: ['currency', 'guild', 'events', 'cosmetics', 'weekly_cap'],
    ui_usage_notes:
      'Use when describing rewards that require guild participation (Guild Events, Red Gold Boutique purchases, or tracking the weekly Treasure Token cap).',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'currency.vintage_bookplate',
    category: 'currency',
    file: 'assets/game/currency/currency-vintage-bookplate.png',
    label: 'Vintage Bookplate',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Voucher currency earned by recycling unused Inner Way tips. Spent on materials and resources for upgrading Inner Ways and related systems.',
    game_system_tags: ['currency', 'inner_way', 'recycling', 'progression'],
    ui_usage_notes:
      'Use when explaining how to convert duplicate tips into long-term power via Inner Way upgrades and tip recycling.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'items.lingering_melody',
    category: 'items',
    file: 'assets/game/items/item-common-lingering-melody.png',
    label: 'Lingering Melody',
    kind: 'gacha-ticket-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Premium gacha ticket used for Celestial Echo draws (the premium banner). Typically purchased with Echo Jade from shops such as Meow Meow’s Shop, Zhao Feiyan’s Warehouse, and Ghostlight Market, and sometimes obtained from passes or bundles fed by Echo Bead top-ups.',
    game_system_tags: ['item', 'gacha_ticket', 'celestial_echo', 'premium'],
    ui_usage_notes:
      'Use whenever a guide or checklist refers to Celestial Echo pulls, premium draws, or advises players how to turn premium currency (Echo Beads → Echo Jade) into banner pulls efficiently.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'items.resonating_melody',
    category: 'items',
    file: 'assets/game/items/item-common-resonating-melody.png',
    label: 'Resonating Melody',
    kind: 'gacha-ticket-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Standard gacha ticket used for Solemn Echo draws (the regular / free banner). Purchased with Echo Jade and used for Solemn Echo pulls and long-term cosmetic or weapon unlocks.',
    game_system_tags: ['item', 'gacha_ticket', 'solemn_echo', 'free_to_play'],
    ui_usage_notes:
      'Use for grindable / Echo-Jade-based gacha pulls and any advice about turning Echo Jade into regular cosmetics, weapons, and other non-premium draws.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'navigation.battle_pass',
    category: 'navigation',
    file: 'assets/game/navigation/battle-pass-icon.png',
    label: 'Battle Pass',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Battle Pass navigation icon leading to the season pass / battle pass progression screen.',
    game_system_tags: ['navigation', 'menu', 'battle_pass', 'season'],
    ui_usage_notes:
      'Use to represent the Battle Pass feature in helper UIs or links to BP-related guides.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.draw',
    category: 'navigation',
    file: 'assets/game/navigation/draw-icon.png',
    label: 'Draw',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gacha / Draw navigation icon used to open Celestial and Solemn Echo draw menus.',
    game_system_tags: ['navigation', 'menu', 'gacha', 'draw'],
    ui_usage_notes: 'Use for anything that opens or references the draw / gacha screen.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.events',
    category: 'navigation',
    file: 'assets/game/navigation/events-icon.png',
    label: 'Events',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Events navigation icon for listing and managing time-limited activities and event rewards.',
    game_system_tags: ['navigation', 'menu', 'events'],
    ui_usage_notes:
      'Use wherever the helper links to live events, event calendars, or event-focused guides.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.journal',
    category: 'navigation',
    file: 'assets/game/navigation/journal-icon.png',
    label: 'Journal',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Journal icon representing the quest log, story progression, and in-game records.',
    game_system_tags: ['navigation', 'menu', 'journal', 'quests'],
    ui_usage_notes: 'Use when representing the quest log / journal in the helper UI.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_appearance',
    category: 'navigation',
    file: 'assets/game/navigation/menu-appearance-icon.png',
    label: 'Appearance',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Appearance / fashion menu icon for outfit, cosmetic, and style management.',
    game_system_tags: ['navigation', 'menu', 'cosmetics', 'appearance'],
    ui_usage_notes:
      'Use for any entry point that talks about appearance sets, outfits, skins, or fashion systems.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_bag',
    category: 'navigation',
    file: 'assets/game/navigation/menu-bag-icon.png',
    label: 'Bag',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Main inventory / bag menu icon used to open the item inventory screen.',
    game_system_tags: ['navigation', 'menu', 'inventory'],
    ui_usage_notes: 'Use when linking to anything about inventory, items, or bag management.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_battle_pass',
    category: 'navigation',
    file: 'assets/game/navigation/menu-battle-pass-icon.png',
    label: 'Battle Pass',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level Battle Pass icon for accessing the season pass from the main menu.',
    game_system_tags: ['navigation', 'menu', 'battle_pass', 'season'],
    ui_usage_notes: 'Use as the main menu button for BP-related helper views.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_compendium',
    category: 'navigation',
    file: 'assets/game/navigation/menu-compendium-icon.png',
    label: 'Compendium',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Guide / Compendium navigation icon for encyclopedic or tutorial content.',
    game_system_tags: ['navigation', 'menu', 'guide'],
    ui_usage_notes: 'Use for WWM Helper sections that act as encyclopedias or multi-topic guides.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_develop',
    category: 'navigation',
    file: 'assets/game/navigation/menu-develop-icon.png',
    label: 'Develop',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Develop menu icon for progression systems like Inner Ways, upgrades, and character development.',
    game_system_tags: ['navigation', 'menu', 'progression'],
    ui_usage_notes:
      'Use when the helper links to Inner Ways, tips, or general power progression tools.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_draw',
    category: 'navigation',
    file: 'assets/game/navigation/menu-draw-icon.png',
    label: 'Draw',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level Draw icon for the gacha hub from the main menu.',
    game_system_tags: ['navigation', 'menu', 'gacha', 'draw'],
    ui_usage_notes: 'Use as the main menu entry point to draw/gacha-related helper content.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_emotes',
    category: 'navigation',
    file: 'assets/game/navigation/menu-emotes-icon.png',
    label: 'Emotes',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Emotes menu icon for expressions and social animations.',
    game_system_tags: ['navigation', 'menu', 'emotes', 'social'],
    ui_usage_notes: 'Use in UI that explains or previews emotes and social expression tools.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_events',
    category: 'navigation',
    file: 'assets/game/navigation/menu-events-icon.png',
    label: 'Events',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level icon for event listings and event management.',
    game_system_tags: ['navigation', 'menu', 'events'],
    ui_usage_notes: 'Use as the button to open any event-focused helper view.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_exit',
    category: 'navigation',
    file: 'assets/game/navigation/menu-exit-icon.png',
    label: 'Exit',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Exit icon usually mapped to closing menus, logging out, or leaving the game/session.',
    game_system_tags: ['navigation', 'menu', 'exit'],
    ui_usage_notes:
      'Use for close / back / exit actions in helper UIs where you want to mimic the in-game affordance.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_feedback',
    category: 'navigation',
    file: 'assets/game/navigation/menu-feedback-icon.png',
    label: 'Feedback',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Feedback icon typically used for bug reports, feedback forms, or support requests.',
    game_system_tags: ['navigation', 'menu', 'feedback'],
    ui_usage_notes: 'Use if you add a feedback link or bug-report function to the helper.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_guide',
    category: 'navigation',
    file: 'assets/game/navigation/menu-guide-icon.png',
    label: 'Guide',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Guide icon for tutorial, help, or guide menus.',
    game_system_tags: ['navigation', 'menu', 'guide'],
    ui_usage_notes: 'Use as the main “Guides” hub entry icon in the helper.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_guild',
    category: 'navigation',
    file: 'assets/game/navigation/menu-guild-icon.png',
    label: 'Guild',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Guild navigation icon for guild management, errands, guild shop, and social structures.',
    game_system_tags: ['navigation', 'menu', 'guild', 'social'],
    ui_usage_notes: 'Use for anything that is clearly guild-only (errands, shops, guild events).',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_menu',
    category: 'navigation',
    file: 'assets/game/navigation/menu-icon.png',
    label: 'Menu',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Generic main menu icon, often used as a hub opening all other menus.',
    game_system_tags: ['navigation', 'menu'],
    ui_usage_notes: 'Use as a generic hamburger/hub menu icon in your helper layout.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_journal',
    category: 'navigation',
    file: 'assets/game/navigation/menu-journal-icon.png',
    label: 'Journal',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level icon for the quest journal and story log.',
    game_system_tags: ['navigation', 'menu', 'journal', 'quests'],
    ui_usage_notes: 'Use when linking directly to quest log / narrative tracking features.',
    width: 1000,
    height: 400,
    aspect_ratio: '5:2',
  },
  {
    id: 'navigation.menu_letter',
    category: 'navigation',
    file: 'assets/game/navigation/menu-letter-icon.png',
    label: 'Letter',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Letter / mail icon for in-game mail, system messages, and rewards.',
    game_system_tags: ['navigation', 'menu', 'mail'],
    ui_usage_notes: 'Use for mail / notification views or reward-collection screens.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_photo',
    category: 'navigation',
    file: 'assets/game/navigation/menu-photo-icon.png',
    label: 'Photo',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Photo / camera icon for snapshot or screenshot-related features.',
    game_system_tags: ['navigation', 'menu', 'photo'],
    ui_usage_notes: 'Use wherever you reference in-game photos, galleries, or captures.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_profession',
    category: 'navigation',
    file: 'assets/game/navigation/menu-profession-icon.png',
    label: 'Profession',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Profession icon for life-skills, careers, and non-combat activities.',
    game_system_tags: ['navigation', 'menu', 'profession'],
    ui_usage_notes: 'Use for crafting, professions, or life-skill dashboards.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_quest',
    category: 'navigation',
    file: 'assets/game/navigation/menu-quest-icon.png',
    label: 'Quest',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Quest navigation icon for main, side, and daily quests.',
    game_system_tags: ['navigation', 'menu', 'quests'],
    ui_usage_notes: 'Use for quest lists, filters, or quest-helper features.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_season',
    category: 'navigation',
    file: 'assets/game/navigation/menu-season-icon.png',
    label: 'Season',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Season menu icon for seasonal activities, shops, and seasonal progression.',
    game_system_tags: ['navigation', 'menu', 'season'],
    ui_usage_notes: 'Use in season-path guides, season currency dashboards, and season timers.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_sects',
    category: 'navigation',
    file: 'assets/game/navigation/menu-sects-icon.png',
    label: 'Sects',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Sects navigation icon for sect selection, progression, and sect-specific systems.',
    game_system_tags: ['navigation', 'menu', 'sects'],
    ui_usage_notes: 'Use for sect comparison tools, guides, or anything related to sect choices.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_settings',
    category: 'navigation',
    file: 'assets/game/navigation/menu-settings-icon.png',
    label: 'Settings',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Settings / options icon for gameplay, graphics, and account options.',
    game_system_tags: ['navigation', 'menu', 'settings'],
    ui_usage_notes: 'Use anywhere that opens configuration, toggles, or preferences.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_shop',
    category: 'navigation',
    file: 'assets/game/navigation/menu-shop-icon.png',
    label: 'Shop',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Shop icon for general in-game shops and purchases.',
    game_system_tags: ['navigation', 'menu', 'shop'],
    ui_usage_notes:
      'Use for generic shop-related helper sections, not for a specific currency-only store.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_social',
    category: 'navigation',
    file: 'assets/game/navigation/menu-social-icon.png',
    label: 'Social',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Social menu icon for friends, teams, partnerships, and other social systems.',
    game_system_tags: ['navigation', 'menu', 'social'],
    ui_usage_notes: 'Use for any helper view focused on social / party / partnership systems.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_time',
    category: 'navigation',
    file: 'assets/game/navigation/menu-time-icon.png',
    label: 'Time',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Time icon used for reset timers, schedule views, or calendar-style UIs.',
    game_system_tags: ['navigation', 'menu', 'time', 'resets'],
    ui_usage_notes: 'Use for daily/weekly reset panels, timer dashboards, or schedule helpers.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_wandering_paths',
    category: 'navigation',
    file: 'assets/game/navigation/menu-wandering-paths-icon.png',
    label: 'Wandering Paths',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Wandering Paths navigation icon for co-op path content and social adventures.',
    game_system_tags: ['navigation', 'menu', 'wandering_paths', 'coop'],
    ui_usage_notes:
      'Use when linking to Wandering Paths explanations, co-op path guides, or adventure-slip farming routes.',
    width: 1000,
    height: 400,
    aspect_ratio: '5:2',
  },
  {
    id: 'navigation.online_mode',
    category: 'navigation',
    file: 'assets/game/navigation/online-mode-icon.png',
    label: 'Online Mode',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Online Mode icon for switching the game into shared-world MMO mode where other players are visible.',
    game_system_tags: ['navigation', 'mode', 'online'],
    ui_usage_notes:
      'Use in helper UIs that talk about toggling between Solo and Online modes, or when describing online-only activities.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.shop',
    category: 'navigation',
    file: 'assets/game/navigation/shop-icon.png',
    label: 'Shop',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Generic shop icon typically used for quick-access shops or featured store entries.',
    game_system_tags: ['navigation', 'menu', 'shop'],
    ui_usage_notes: 'Use for quick shop shortcuts or non-menu-bar shop buttons.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.solo_mode',
    category: 'navigation',
    file: 'assets/game/navigation/solo-mode-icon.png',
    label: 'Solo Mode',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Solo Mode icon for switching into an isolated / non-shared world experience.',
    game_system_tags: ['navigation', 'mode', 'solo'],
    ui_usage_notes:
      'Use wherever you talk about Solo vs Online modes or single-player-only activities.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'sect_paths.bamboocut_wind',
    category: 'sect_paths',
    file: 'assets/game/sect-paths/bamboocut-wind.png',
    label: 'Bamboocut – Wind Path',
    kind: 'path-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Assassin-style melee DPS path focused on high-speed burst and mobility, often pairing Infernal Twinblades and Mortal Rope Dart. Leans towards PvP-style aggressive gameplay.',
    game_system_tags: ['path', 'martial', 'assassin', 'melee', 'pvp'],
    ui_usage_notes:
      'Use on guides about burst / assassin builds, especially when recommending Bamboocut – Wind for aggressive players.',
    width: 542,
    height: 158,
    aspect_ratio: '271:79',
  },
  {
    id: 'sect_paths.bellstrike_splendor',
    category: 'sect_paths',
    file: 'assets/game/sect-paths/bellstrike-splendor.png',
    label: 'Bellstrike – Splendor Path',
    kind: 'path-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Mobile melee DPS path for Nameless Sword + Nameless Spear. Emphasizes fluid combos, repositioning, and consistent damage with strong mobility tools.',
    game_system_tags: ['path', 'martial', 'melee', 'hybrid', 'dps'],
    ui_usage_notes:
      'Use when talking about Bellstrike Splendor breakthrough, related tips, or path-progression advice for Nameless Sword builds.',
    width: 546,
    height: 158,
    aspect_ratio: '273:79',
  },
  {
    id: 'sect_paths.bellstrike_umbra',
    category: 'sect_paths',
    file: 'assets/game/sect-paths/bellstrike-umbra.png',
    label: 'Bellstrike – Umbra Path',
    kind: 'path-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bleed-centric melee DPS path often pairing Strategic Sword with Heavenquaker Spear. Focuses on stacking bleed marks and detonating them for huge burst damage.',
    game_system_tags: ['path', 'martial', 'melee', 'bleed', 'dps'],
    ui_usage_notes:
      'Use in high-damage bleed-stacking build writeups or when illustrating Bellstrike – Umbra meta combos.',
    width: 546,
    height: 158,
    aspect_ratio: '273:79',
  },
  {
    id: 'sect_paths.silkbind_deluge',
    category: 'sect_paths',
    file: 'assets/game/sect-paths/silkbind-deluge.png',
    label: 'Silkbind – Deluge Path',
    kind: 'path-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Ranged healer/support path focused on sustain and revives, typically using Soulshade Umbrella + Panacea Fan. Excels in co-op content and keeping teams alive.',
    game_system_tags: ['path', 'martial', 'healer', 'support', 'ranged', 'coop'],
    ui_usage_notes:
      'Use for healing-oriented build sections, co-op support recommendations, or Path Guide content about Silkbind – Deluge.',
    width: 546,
    height: 162,
    aspect_ratio: '91:27',
  },
  {
    id: 'sect_paths.silkbind_jade',
    category: 'sect_paths',
    file: 'assets/game/sect-paths/silkbind-jade.png',
    label: 'Silkbind – Jade Path',
    kind: 'path-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Ranged crowd-control DPS path using Vernal Umbrella + Inkwell Fan. Specializes in juggling humanoid enemies and controlling fights from a distance.',
    game_system_tags: ['path', 'martial', 'ranged', 'cc', 'control'],
    ui_usage_notes:
      'Use when describing CC-heavy ranged playstyles or stylish control builds for solo and group play.',
    width: 546,
    height: 162,
    aspect_ratio: '91:27',
  },
  {
    id: 'sect_paths.stonesplit_might',
    category: 'sect_paths',
    file: 'assets/game/sect-paths/stonesplit-might.png',
    label: 'Stonesplit – Might Path',
    kind: 'path-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Tank-oriented path focusing on damage mitigation and control, commonly using Thundercry Blade with Stormbreaker Spear. Designed to absorb damage, hold aggro, and group enemies for AoE.',
    game_system_tags: ['path', 'martial', 'tank', 'defense', 'coop'],
    ui_usage_notes:
      'Use when explaining tank builds, group front-line roles, or Stonesplit – Might progression tips.',
    width: 546,
    height: 158,
    aspect_ratio: '273:79',
  },
  {
    id: 'system.energy',
    category: 'system',
    file: 'assets/game/system/energy.png',
    label: 'Energy',
    kind: 'system-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Account-wide activity resource that gates certain high-value tasks (similar to stamina systems in other online games). Regenerates over time and is spent on repeatable, reward-heavy content such as Campaigns, Outposts, and Sword Trials.',
    game_system_tags: ['system', 'resource', 'daily', 'account_wide'],
    ui_usage_notes:
      'Use wherever the helper references daily/weekly energy spending priorities, capped-content planning, or reminders to avoid wasting Energy at cap.',
    width: 644,
    height: 224,
    aspect_ratio: '23:8',
  },
  {
    id: 'system.stamina',
    category: 'system',
    file: 'assets/game/system/stamina.png',
    label: 'Stamina',
    kind: 'system-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Crafting stamina used when forging gear, cooking, brewing medicine, construction, and other production tasks. Each craft consumes Stamina, which replenishes once per day at the scheduled daily reset.',
    game_system_tags: ['system', 'resource', 'daily', 'crafting', 'profession'],
    ui_usage_notes:
      'Use for anything that talks about crafting limits, daily Stamina refills, or optimizing forge / medicine / cooking batches. Do not use for movement or dodge stamina.',
    width: 748,
    height: 228,
    aspect_ratio: '187:57',
  },
  {
    id: 'currency.reputation',
    category: 'currency',
    file: 'assets/game/currency/currency-reputation.png',
    label: 'Reputation',
    kind: 'currency-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Sect reputation currency earned from completing Sect Commands (Jianghu Errands) and other daily sect activities. Spent at sect shops on sect-specific cosmetics, materials, and rewards; capped weekly.',
    game_system_tags: ['currency', 'sects', 'reputation', 'special', 'weekly_cap'],
    ui_usage_notes:
      'Use for any guide or checklist that references Sect Commands, sect reputation caps, or spending in sect shops.',
    width: 560,
    height: 480,
    aspect_ratio: '7:6',
  },
  {
    id: 'system.energy_small',
    category: 'system',
    file: 'assets/game/system/energy-small.png',
    label: 'Energy (Small)',
    kind: 'system-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Account-wide activity resource that gates certain high-value tasks (similar to stamina systems in other online games). Regenerates over time and is spent on repeatable, reward-heavy content.',
    game_system_tags: ['system', 'resource', 'daily', 'account_wide'],
    ui_usage_notes:
      'Compact Energy icon for checklists, tooltips, and tight HUD-style layouts where the full Energy graphic would be too large.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'system.stamina_small',
    category: 'system',
    file: 'assets/game/system/stamina-small.png',
    label: 'Stamina (Crafting)',
    kind: 'system-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Crafting Stamina icon for forge, cooking, medicine, manuals, and construction UIs. Represents the limited daily pool that refills at the daily reset.',
    game_system_tags: ['system', 'resource', 'daily', 'crafting', 'profession'],
    ui_usage_notes:
      'Use in tight layouts like checklists, tooltips, or inline text when referencing crafting Stamina costs or remaining daily Stamina.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
    // INNER WAY ICONS
  {
    id: 'inner_way.sword_morph',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-sword-morph.png',
    label: 'Sword Morph',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Splendor Inner Way that upgrades Nameless Sword’s Charged Skill Vagrant Sword, firing extra sword energy when charged with a Qi shield and allowing you to spend extra Endurance to boost its damage.',
    game_system_tags: ['inner_way', 'bellstrike_splendor', 'attack', 'martial_arts', 'damage_boost'],
    ui_usage_notes:
      'Use on guides or builds focused on Nameless Sword charged attacks and Bellstrike – Splendor burst setups.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.battle_anthem',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-battle-anthem.png',
    label: 'Battle Anthem',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Splendor Inner Way that increases damage dealt by Charged Skills against bosses, improving sustained boss DPS for melee builds.',
    game_system_tags: ['inner_way', 'bellstrike_splendor', 'attack', 'damage_boost', 'boss'],
    ui_usage_notes:
      'Use when highlighting boss-focused Bellstrike – Splendor builds or Inner Way recommendations for melee DPS.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.adaptive_steel',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-adaptive-steel.png',
    label: 'Adaptive Steel',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Umbra Inner Way that grants a special Martial Skill depending on the equipped blade weapon; sword and dual blades each gain their own timed Martial Skill with separate cooldowns.',
    game_system_tags: ['inner_way', 'bellstrike_umbra', 'attack', 'support', 'buff'],
    ui_usage_notes:
      'Use for explanations of Adaptive Steel oddity unlocks and as a callout for bleed/umbra sword builds that swap blades.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.morale_chant',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-morale-chant.png',
    label: 'Morale Chant',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Legendary General Inner Way that grants stacks of Yi River when attacking or healing, increasing Physical Damage and healing for a duration, with stacks building over time.',
    game_system_tags: ['inner_way', 'general', 'attack', 'buff', 'stacking'],
    ui_usage_notes:
      'Use wherever you explain universal DPS / healer Inner Ways or Echo Jade investment into Morale Chant pages and notes.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.echoes_of_oblivion',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-echoes-of-oblivion.png',
    label: 'Echoes of Oblivion',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bamboocut – Wind Legendary Inner Way for Infernal Twinblades that applies Sin and Karma on light attacks; striking enemies marked with both debuffs lets your attacks ignore a portion of their defenses.',
    game_system_tags: ['inner_way', 'bamboocut_wind', 'attack', 'debuff', 'defense_shred'],
    ui_usage_notes:
      'Use on high-end Bamboocut Twinblade guides that talk about Sin/Karma management and armor-shred combos.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.evasive_charge',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-evasive-charge.png',
    label: 'Evasive Charge',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that gives a chance to refund all Endurance spent after a Perfect Dodge, rewarding precise evasions with more stamina for follow-up attacks.',
    game_system_tags: ['inner_way', 'general', 'cost_reduction', 'recover', 'dodge', 'endurance'],
    ui_usage_notes:
      'Use in survivability / dodge-tech sections or beginner Inner Way recommendations that emphasize learning Perfect Dodges.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.envigorated_warrior',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-envigorated-warrior.png',
    label: 'Envigorated Warrior',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that passively increases all damage and healing done, but disables the buff briefly after being hit and applies a Cage debuff that increases damage taken.',
    game_system_tags: ['inner_way', 'general', 'attack', 'buff', 'damage_boost', 'risk_reward'],
    ui_usage_notes:
      'Use when discussing glass-cannon style Inner Way setups or Still Shore quest rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.bitter_seasons',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-bitter-seasons.png',
    label: 'Bitter Seasons',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that adds a chance for your attacks to inflict a Poison DoT which also stacks a Physical Defense reduction on the target up to several layers.',
    game_system_tags: ['inner_way', 'general', 'attack', 'debuff', 'poison', 'stacking'],
    ui_usage_notes:
      'Use for DoT / debuff-oriented builds or when explaining Gleaming Abyss rewards and Mist Gate exploration.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.divine_roulette',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-divine-roulette.png',
    label: 'Divine Roulette',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that, after a successful deflect, grants one of several buffs that empower your next skill within a short window; can only trigger periodically.',
    game_system_tags: ['inner_way', 'general', 'counter', 'buff', 'damage_boost', 'deflect'],
    ui_usage_notes:
      'Use in parry/deflect tech sections or Gleaming Abyss Inner Way callouts where you highlight reactive playstyles.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.fury_harvest',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-fury-harvest.png',
    label: 'Fury Harvest',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way for Mystic Arts that gives certain recovery actions a chance to grant extra Vitality, increasing how often you can cast Mystic Arts without relying on attacks or parries.',
    game_system_tags: ['inner_way', 'general', 'support', 'mystic_arts', 'vitality', 'recover'],
    ui_usage_notes:
      'Use when talking about Mystic Art uptime, Vitality management, or the Lost Chapter questline in Bodhi Sea.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.vital_leech',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-vital-leech.png',
    label: 'Vital Leech',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that lets Exhaustion Execution skills restore a portion of HP based on the damage dealt, turning executions into strong self-heals.',
    game_system_tags: ['inner_way', 'general', 'pursuit', 'recover', 'execution'],
    ui_usage_notes:
      'Use for melee sustain build guides or notes about Palace of Annals Lost Chapter rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.restoring_blossom',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-restoring-blossom.png',
    label: 'Restoring Blossom',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Deluge Inner Way that makes critical heals apply Nurturing stacks, increasing healing received for a short time and stacking several times.',
    game_system_tags: ['inner_way', 'silkbind_deluge', 'support', 'heal', 'stacking'],
    ui_usage_notes:
      'Use on healer build write-ups, especially when covering Healer’s Union unlock steps and crit-healing synergies.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.royal_remedy',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-royal-remedy.png',
    label: 'Royal Remedy',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Deluge Inner Way for Panacea Fan that boosts the healing from Cloudburst Healing’s water clone and generates Dewdrops for allies healed within its area.',
    game_system_tags: ['inner_way', 'silkbind_deluge', 'support', 'heal', 'dewdrop'],
    ui_usage_notes:
      'Use in Panacea Fan healer guides or Inner Way overviews explaining Dewdrop-based sustain tools.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.blossom_barrage',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-blossom-barrage.png',
    label: 'Blossom Barrage',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Jade Legendary Inner Way that gives Vernal Umbrella’s Spring Sorrow extra charges and applies a debuff making enemies take increased damage from specific ballistic skills.',
    game_system_tags: ['inner_way', 'silkbind_jade', 'attack', 'martial_arts', 'damage_boost'],
    ui_usage_notes:
      'Use for ranged control/DPS Vernal Umbrella builds or when describing Shadows in Bloom quest rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.thunderous_bloom',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-thunderous-bloom.png',
    label: 'Thunderous Bloom',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Jade Inner Way that rewards moving a set distance quickly by granting Spring Thunder, buffing the damage of your next few Heavy or Airborne Heavy Attacks.',
    game_system_tags: ['inner_way', 'silkbind_jade', 'damage_boost', 'buff', 'movement'],
    ui_usage_notes:
      'Use in mobile ranged build sections or Mercyheart Monastery outpost reward callouts.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.seasonal_edge',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-seasonal-edge.png',
    label: 'Seasonal Edge',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that grants one of several offensive buffs after casting a dual-weapon skill, giving flexible damage bonuses for dual-wield setups.',
    game_system_tags: ['inner_way', 'general', 'attack', 'buff', 'damage_boost', 'dual_weapon'],
    ui_usage_notes:
      'Use when covering Kaifeng Fairgrounds calligraphy shop purchases or dual-weapon Inner Way synergies.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.insightful_strike',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-insightful-strike.png',
    label: 'Insightful Strike',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Umbra Inner Way where dealing Affinity damage builds Focus; at max Focus you enter Concentration, boosting Affinity damage and occasionally reducing damage taken.',
    game_system_tags: ['inner_way', 'bellstrike_umbra', 'attack', 'damage_boost', 'defense'],
    ui_usage_notes:
      'Use for Strategic Sword bleed/affinity builds or when explaining Feng Jisheng’s archery challenge rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.sword_horizon',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-sword-horizon.png',
    label: 'Sword Horizon',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Umbra Legendary Inner Way for Strategic Sword that adds a timing-based follow-up attack after Martial, Special, or Charged Skills; consuming Bleed stacks for a large burst when fully stacked.',
    game_system_tags: ['inner_way', 'bellstrike_umbra', 'attack', 'martial_arts', 'pursuit', 'bleed'],
    ui_usage_notes:
      'Use when highlighting high-skill Bellstrike combos or Ghostlight Market Unknown Old Book farming routes.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.exquisite_scenery',
    category: 'inner_way',
    file: 'assets/game/inner-way/inner-way-exquisite-scenery.png',
    label: 'Exquisite Scenery',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Stonesplit – Might Inner Way that turns successful Thundercry Blade blocks into a special counter, letting you instantly fire a first-stage charged heavy and restoring Battle Will when you land varied combos.',
    game_system_tags: ['inner_way', 'stonesplit_might', 'defense', 'martial_arts', 'counter'],
    ui_usage_notes:
      'Use in tank build write-ups focused on Thundercry Blade counterplay and Northern Vow Ruins monk encounter rewards.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
    {
    id: 'inner_way.flying_gourds',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-flying-gourds.png',
    label: 'Flying Gourds',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Silkbind – Jade Inner Way that adds a second charge to Inkwell Fan's Martial Arts Skill Peak's Springless Silence at the cost of a slightly longer cooldown.",
    game_system_tags: ['inner_way', 'path', 'martial', 'ranged', 'support'],
    ui_usage_notes:
      'Use when describing Silkbind – Jade builds that double up on Springless Silence casts or discuss fan/umbrella control-support setups.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.mountains_might',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-mountains-might.png',
    label: "Mountain's Might",
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Bellstrike – Splendor Inner Way that lets Noname Spear's Qiankun's Lock grant the Endless Gale effect, increasing its Endurance cost reduction window for a short time.",
    game_system_tags: ['inner_way', 'path', 'martial', 'melee', 'support'],
    ui_usage_notes:
      'Use in Bellstrike – Splendor spear build notes, especially when talking about Endurance-saving loops and Qiankun’s Lock optimization.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.riptide_reflex',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-riptide-reflex.png',
    label: 'Riptide Reflex',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bamboocut – Wind Inner Way that briefly reduces the cooldown of your current Martial Arts Skill whenever you land a hit with a qualifying control skill, with an internal cooldown.',
    game_system_tags: ['inner_way', 'path', 'martial', 'assassin', 'melee', 'control', 'cc'],
    ui_usage_notes:
      'Use in assassin/Infernal Twinblades path guides when highlighting control-skill chains and Martial Arts uptime improvements.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.fivefold_bleed',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-fivefold-bleed.png',
    label: 'Fivefold Bleed',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General Inner Way that lets attacks occasionally apply Weeping Blood stacks which deal periodic damage; at five stacks the effect detonates for a single strong hit.',
    game_system_tags: ['inner_way', 'bleed', 'dps'],
    ui_usage_notes:
      'Use wherever you talk about bleed-centric builds, bleed detonations, or generic DPS Inner Ways that work across multiple paths.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.shadow_assault',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-shadow-assault.png',
    label: 'Shadow Assault',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "General Inner Way focused on assassin Mystic Arts, extending the ambush range of Touch of Death so you can open from farther away.",
    game_system_tags: ['inner_way', 'assassin', 'dps'],
    ui_usage_notes:
      'Use when covering stealth/assassin Mystic Art setups or long-range ambush openers in build guides.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.wildfire_spark',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-wildfire-spark.png',
    label: 'Wildfire Spark',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bellstrike – Splendor Inner Way that refunds a small percentage of Endurance whenever you spend it, turning heavy Endurance use into extra sustain.',
    game_system_tags: ['inner_way', 'path', 'martial', 'melee', 'support'],
    ui_usage_notes:
      'Use on Bellstrike Splendor guides that emphasize Endurance-hungry combos or QoL sustain for repeated charged skills and dodges.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.star_reacher',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-star-reacher.png',
    label: 'Star Reacher',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Silkbind – Jade Inner Way that grants a short Physical Attack bonus after you knock an enemy airborne, rewarding frequent juggles.',
    game_system_tags: ['inner_way', 'path', 'martial', 'ranged', 'dps'],
    ui_usage_notes:
      'Use in ranged umbrella/fan build notes that revolve around launching targets and capitalizing on airborne windows.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.mending_loom',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-mending-loom.png',
    label: 'Mending Loom',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Silkbind – Deluge Inner Way that enhances Soulshade Umbrella's Special Skill Echoing Grow, restoring Dewdrops and providing extra healing based on Dewdrops spent.",
    game_system_tags: ['inner_way', 'path', 'healer', 'support', 'ranged'],
    ui_usage_notes:
      'Use for healer-focused guides where Dewdrop economy and burst healing from Echoing Grow are important talking points.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.evening_snow',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-evening-snow.png',
    label: 'Evening Snow',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General defensive Inner Way that, early in combat, automatically grants a short self-heal-over-time if your HP drops under a threshold, with a long cooldown.',
    game_system_tags: ['inner_way', 'support', 'healer', 'defense'],
    ui_usage_notes:
      'Use when explaining safety nets for new players, solo-survivability picks, or “panic button” passives in general Inner Way recommendations.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.trapped_beast',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-trapped-beast.png',
    label: 'Trapped Beast',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Stonesplit – Might Inner Way that, when you are very low on HP, creates a large temporary shield once in a long while, helping tanks survive lethal bursts.',
    game_system_tags: ['inner_way', 'path', 'tank', 'defense', 'melee'],
    ui_usage_notes:
      'Use for tank / Stonesplit Might writeups that highlight emergency shielding or last-stand mechanics.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.esoteric_revival',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-esoteric-revival.png',
    label: 'Esoteric Revival',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Silkbind – Deluge Inner Way that boosts the healing of Panacea Fan's Resurrection Perception Skill on revived allies, making its revive much stronger.",
    game_system_tags: ['inner_way', 'path', 'healer', 'support', 'ranged'],
    ui_usage_notes:
      'Use in co-op healer guides when emphasizing strong combat revives or clutch recovery tools.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.breaking_point',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-breaking-point.png',
    label: 'Breaking Point',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Bamboocut – Wind Inner Way that adds Disintegration stacks when you crit Exhausted enemies, granting Physical Penetration and extra Critical Damage up to a small cap.',
    game_system_tags: ['inner_way', 'path', 'martial', 'assassin', 'melee', 'dps'],
    ui_usage_notes:
      'Use on high-crit assassin build sections that talk about shredding defenses and scaling crit damage against staggered targets.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.vendetta',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-vendetta.png',
    label: 'Vendetta',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Bamboocut – Wind Inner Way that extends Guided Blade's Vendetta Token duration and refunds Token of Gratitudes, smoothing out resource flow.",
    game_system_tags: ['inner_way', 'path', 'martial', 'assassin', 'melee', 'support'],
    ui_usage_notes:
      'Use where you cover Guided Blade/Bamboocut token management, especially for longer boss fights and resource sustain.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.steadfast_stance',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-steadfast-stance.png',
    label: 'Steadfast Stance',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General defensive Inner Way that reduces the chance of being staggered by most enemy hits (excluding bosses and players).',
    game_system_tags: ['inner_way', 'defense', 'tank'],
    ui_usage_notes:
      'Use when suggesting generic anti-flinch tech for PvE builds, especially for players who dislike being interrupted by trash mobs.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.wind_beneath_wings',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-wind-beneath-wings.png',
    label: 'Wind Beneath Wings',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'General mobility Inner Way that lowers Skywalk Dash Endurance cost while jumping, briefly boosts move speed after landing, and heals a bit of HP whenever you defeat an enemy.',
    game_system_tags: ['inner_way', 'support', 'defense'],
    ui_usage_notes:
      'Use for movement-focused or exploration builds where cheaper dashes, speed bursts, and incidental healing matter.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.wolfchasers_art',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-wolfchasers-art.png',
    label: "Wolfchaser's Art",
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Bellstrike – Umbra Inner Way that lowers the combo requirement for Heavenquaker Spear's Sorrow Without Wine buff and can rapidly build combo count when hitting bleeding bosses.",
    game_system_tags: ['inner_way', 'path', 'martial', 'melee', 'bleed', 'dps'],
    ui_usage_notes:
      'Use for spear/Bellstrike Umbra bleed builds where Sorrow Without Wine uptime and boss-focused combos are key.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.art_of_resistance',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-art-of-resistance.png',
    label: 'Art of Resistance',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Stonesplit – Might Inner Way that lengthens the duration of your HP shields and their attached bonus effects, making shield-based skills last longer.',
    game_system_tags: ['inner_way', 'path', 'tank', 'defense'],
    ui_usage_notes:
      'Use in tank guides that emphasize shielding tools, prolonged mitigation, or shield-synergy Stonesplit builds.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
  {
    id: 'inner_way.rock_solid',
    category: 'inner_way',
    file: 'assets/game/inner-ways/inner-way-rock-solid.png',
    label: 'Rock Solid',
    kind: 'inner-way-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      "Stonesplit – Might Inner Way that boosts Roar of Storm's damage reduction after you taunt, stacking higher against bosses but slightly lowering your own damage while the reduction is active.",
    game_system_tags: ['inner_way', 'path', 'tank', 'defense'],
    ui_usage_notes:
      'Use when showcasing classic front-line Stonesplit tanks who trade personal damage for big damage reduction and aggro tools.',
    width: 520,
    height: 800,
    aspect_ratio: '13:20',
  },
];
