import { GameAssetDefinition } from "../../models";

export const NAVIGATION_ASSETS: GameAssetDefinition[] = [
{
    id: 'navigation.battle_pass',
    category: 'navigation',
    file: 'assets/game/navigation/battle-pass-icon.png',
    label: 'Battle Pass',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Battle Pass navigation icon leading to the season pass / battle pass progression screen.',
    game_system_tags: ['navigation', 'menu', 'battle_pass', 'season'],
    ui_usage_notes:
      'Use to represent the Battle Pass feature in helper UIs or links to BP-related guides.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.draw',
    category: 'navigation',
    file: 'assets/game/navigation/draw-icon.png',
    label: 'Draw',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Gacha / Draw navigation icon used to open Celestial and Solemn Echo draw menus.',
    game_system_tags: ['navigation', 'menu', 'gacha', 'draw'],
    ui_usage_notes: 'Use for anything that opens or references the draw / gacha screen.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.events',
    category: 'navigation',
    file: 'assets/game/navigation/events-icon.png',
    label: 'Events',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Events navigation icon for listing and managing time-limited activities and event rewards.',
    game_system_tags: ['navigation', 'menu', 'events'],
    ui_usage_notes:
      'Use wherever the helper links to live events, event calendars, or event-focused guides.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.journal',
    category: 'navigation',
    file: 'assets/game/navigation/journal-icon.png',
    label: 'Journal',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Journal icon representing the quest log, story progression, and in-game records.',
    game_system_tags: ['navigation', 'menu', 'journal', 'quests'],
    ui_usage_notes: 'Use when representing the quest log / journal in the helper UI.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_appearance',
    category: 'navigation',
    file: 'assets/game/navigation/menu-appearance-icon.png',
    label: 'Appearance',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Appearance / fashion menu icon for outfit, cosmetic, and style management.',
    game_system_tags: ['navigation', 'menu', 'cosmetics', 'appearance'],
    ui_usage_notes:
      'Use for any entry point that talks about appearance sets, outfits, skins, or fashion systems.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_bag',
    category: 'navigation',
    file: 'assets/game/navigation/menu-bag-icon.png',
    label: 'Bag',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Main inventory / bag menu icon used to open the item inventory screen.',
    game_system_tags: ['navigation', 'menu', 'inventory'],
    ui_usage_notes: 'Use when linking to anything about inventory, items, or bag management.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_battle_pass',
    category: 'navigation',
    file: 'assets/game/navigation/menu-battle-pass-icon.png',
    label: 'Battle Pass',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level Battle Pass icon for accessing the season pass from the main menu.',
    game_system_tags: ['navigation', 'menu', 'battle_pass', 'season'],
    ui_usage_notes: 'Use as the main menu button for BP-related helper views.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_compendium',
    category: 'navigation',
    file: 'assets/game/navigation/menu-compendium-icon.png',
    label: 'Compendium',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Guide / Compendium navigation icon for encyclopedic or tutorial content.',
    game_system_tags: ['navigation', 'menu', 'guide'],
    ui_usage_notes: 'Use for WWM Helper sections that act as encyclopedias or multi-topic guides.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_develop',
    category: 'navigation',
    file: 'assets/game/navigation/menu-develop-icon.png',
    label: 'Develop',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Develop menu icon for progression systems like Inner Ways, upgrades, and character development.',
    game_system_tags: ['navigation', 'menu', 'progression'],
    ui_usage_notes:
      'Use when the helper links to Inner Ways, tips, or general power progression tools.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_draw',
    category: 'navigation',
    file: 'assets/game/navigation/menu-draw-icon.png',
    label: 'Draw',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level Draw icon for the gacha hub from the main menu.',
    game_system_tags: ['navigation', 'menu', 'gacha', 'draw'],
    ui_usage_notes: 'Use as the main menu entry point to draw/gacha-related helper content.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_emotes',
    category: 'navigation',
    file: 'assets/game/navigation/menu-emotes-icon.png',
    label: 'Emotes',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Emotes menu icon for expressions and social animations.',
    game_system_tags: ['navigation', 'menu', 'emotes', 'social'],
    ui_usage_notes: 'Use in UI that explains or previews emotes and social expression tools.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_events',
    category: 'navigation',
    file: 'assets/game/navigation/menu-events-icon.png',
    label: 'Events',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level icon for event listings and event management.',
    game_system_tags: ['navigation', 'menu', 'events'],
    ui_usage_notes: 'Use as the button to open any event-focused helper view.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_exit',
    category: 'navigation',
    file: 'assets/game/navigation/menu-exit-icon.png',
    label: 'Exit',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Exit icon usually mapped to closing menus, logging out, or leaving the game/session.',
    game_system_tags: ['navigation', 'menu', 'exit'],
    ui_usage_notes:
      'Use for close / back / exit actions in helper UIs where you want to mimic the in-game affordance.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_feedback',
    category: 'navigation',
    file: 'assets/game/navigation/menu-feedback-icon.png',
    label: 'Feedback',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Feedback icon typically used for bug reports, feedback forms, or support requests.',
    game_system_tags: ['navigation', 'menu', 'feedback'],
    ui_usage_notes: 'Use if you add a feedback link or bug-report function to the helper.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_guide',
    category: 'navigation',
    file: 'assets/game/navigation/menu-guide-icon.png',
    label: 'Guide',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Guide icon for tutorial, help, or guide menus.',
    game_system_tags: ['navigation', 'menu', 'guide'],
    ui_usage_notes: 'Use as the main “Guides” hub entry icon in the helper.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_guild',
    category: 'navigation',
    file: 'assets/game/navigation/menu-guild-icon.png',
    label: 'Guild',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Guild navigation icon for guild management, errands, guild shop, and social structures.',
    game_system_tags: ['navigation', 'menu', 'guild', 'social'],
    ui_usage_notes: 'Use for anything that is clearly guild-only (errands, shops, guild events).',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_menu',
    category: 'navigation',
    file: 'assets/game/navigation/menu-icon.png',
    label: 'Menu',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Generic main menu icon, often used as a hub opening all other menus.',
    game_system_tags: ['navigation', 'menu'],
    ui_usage_notes: 'Use as a generic hamburger/hub menu icon in your helper layout.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_journal',
    category: 'navigation',
    file: 'assets/game/navigation/menu-journal-icon.png',
    label: 'Journal',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Menu-level icon for the quest journal and story log.',
    game_system_tags: ['navigation', 'menu', 'journal', 'quests'],
    ui_usage_notes: 'Use when linking directly to quest log / narrative tracking features.',
    width: 1000,
    height: 400,
    aspect_ratio: '5:2',
  },
  {
    id: 'navigation.menu_letter',
    category: 'navigation',
    file: 'assets/game/navigation/menu-letter-icon.png',
    label: 'Letter',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Letter / mail icon for in-game mail, system messages, and rewards.',
    game_system_tags: ['navigation', 'menu', 'mail'],
    ui_usage_notes: 'Use for mail / notification views or reward-collection screens.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_photo',
    category: 'navigation',
    file: 'assets/game/navigation/menu-photo-icon.png',
    label: 'Photo',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Photo / camera icon for snapshot or screenshot-related features.',
    game_system_tags: ['navigation', 'menu', 'photo'],
    ui_usage_notes: 'Use wherever you reference in-game photos, galleries, or captures.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_profession',
    category: 'navigation',
    file: 'assets/game/navigation/menu-profession-icon.png',
    label: 'Profession',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Profession icon for life-skills, careers, and non-combat activities.',
    game_system_tags: ['navigation', 'menu', 'profession'],
    ui_usage_notes: 'Use for crafting, professions, or life-skill dashboards.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_quest',
    category: 'navigation',
    file: 'assets/game/navigation/menu-quest-icon.png',
    label: 'Quest',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Quest navigation icon for main, side, and daily quests.',
    game_system_tags: ['navigation', 'menu', 'quests'],
    ui_usage_notes: 'Use for quest lists, filters, or quest-helper features.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_season',
    category: 'navigation',
    file: 'assets/game/navigation/menu-season-icon.png',
    label: 'Season',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Season menu icon for seasonal activities, shops, and seasonal progression.',
    game_system_tags: ['navigation', 'menu', 'season'],
    ui_usage_notes: 'Use in season-path guides, season currency dashboards, and season timers.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_sects',
    category: 'navigation',
    file: 'assets/game/navigation/menu-sects-icon.png',
    label: 'Sects',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Sects navigation icon for sect selection, progression, and sect-specific systems.',
    game_system_tags: ['navigation', 'menu', 'sects'],
    ui_usage_notes: 'Use for sect comparison tools, guides, or anything related to sect choices.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_settings',
    category: 'navigation',
    file: 'assets/game/navigation/menu-settings-icon.png',
    label: 'Settings',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Settings / options icon for gameplay, graphics, and account options.',
    game_system_tags: ['navigation', 'menu', 'settings'],
    ui_usage_notes: 'Use anywhere that opens configuration, toggles, or preferences.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_shop',
    category: 'navigation',
    file: 'assets/game/navigation/menu-shop-icon.png',
    label: 'Shop',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Shop icon for general in-game shops and purchases.',
    game_system_tags: ['navigation', 'menu', 'shop'],
    ui_usage_notes:
      'Use for generic shop-related helper sections, not for a specific currency-only store.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_social',
    category: 'navigation',
    file: 'assets/game/navigation/menu-social-icon.png',
    label: 'Social',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Social menu icon for friends, teams, partnerships, and other social systems.',
    game_system_tags: ['navigation', 'menu', 'social'],
    ui_usage_notes: 'Use for any helper view focused on social / party / partnership systems.',
    width: 520,
    height: 400,
    aspect_ratio: '13:10',
  },
  {
    id: 'navigation.menu_time',
    category: 'navigation',
    file: 'assets/game/navigation/menu-time-icon.png',
    label: 'Time',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Time icon used for reset timers, schedule views, or calendar-style UIs.',
    game_system_tags: ['navigation', 'menu', 'time', 'resets'],
    ui_usage_notes: 'Use for daily/weekly reset panels, timer dashboards, or schedule helpers.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.menu_wandering_paths',
    category: 'navigation',
    file: 'assets/game/navigation/menu-wandering-paths-icon.png',
    label: 'Wandering Paths',
    kind: 'menu-nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Wandering Paths navigation icon for co-op path content and social adventures.',
    game_system_tags: ['navigation', 'menu', 'wandering_paths', 'coop'],
    ui_usage_notes:
      'Use when linking to Wandering Paths explanations, co-op path guides, or adventure-slip farming routes.',
    width: 1000,
    height: 400,
    aspect_ratio: '5:2',
  },
  {
    id: 'navigation.online_mode',
    category: 'navigation',
    file: 'assets/game/navigation/online-mode-icon.png',
    label: 'Online Mode',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Online Mode icon for switching the game into shared-world MMO mode where other players are visible.',
    game_system_tags: ['navigation', 'mode', 'online'],
    ui_usage_notes:
      'Use in helper UIs that talk about toggling between Solo and Online modes, or when describing online-only activities.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.shop',
    category: 'navigation',
    file: 'assets/game/navigation/shop-icon.png',
    label: 'Shop',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description:
      'Generic shop icon typically used for quick-access shops or featured store entries.',
    game_system_tags: ['navigation', 'menu', 'shop'],
    ui_usage_notes: 'Use for quick shop shortcuts or non-menu-bar shop buttons.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
  {
    id: 'navigation.solo_mode',
    category: 'navigation',
    file: 'assets/game/navigation/solo-mode-icon.png',
    label: 'Solo Mode',
    kind: 'nav-icon',
    source: 'Where Winds Meet (in-game capture)',
    description: 'Solo Mode icon for switching into an isolated / non-shared world experience.',
    game_system_tags: ['navigation', 'mode', 'solo'],
    ui_usage_notes:
      'Use wherever you talk about Solo vs Online modes or single-player-only activities.',
    width: 200,
    height: 200,
    aspect_ratio: '1:1',
  },
];
