import { Routes } from '@angular/router';
import {
  GuidesHubComponent,
  PrivacyComponent,
  TradingGuideComponent,
  PathSeasonGuideComponent,
  MapComponent,
  ToolsHubComponent,
  ChineseChessComponent,
  ChessWinsGuideComponent,
  HomeComponent,
  TimersComponent,
  ChecklistComponent,
  MultiDayRewardsGuideComponent,
  SettingsIoComponent,
  BossTalentsGuideComponent,
  MysticSkillMaterialsGuideComponent,
  MysticUpgradePlannerComponent,
  MysticMetricsGuideComponent,
} from './components';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'home' },
  { path: 'home', component: HomeComponent },
  { path: 'timers', component: TimersComponent },
  { path: 'checklist', component: ChecklistComponent },
  { path: 'map', component: MapComponent },
  { path: 'guides', component: GuidesHubComponent },
  { path: 'guides/boss-talents', component: BossTalentsGuideComponent },
  { path: 'guides/chess-wins', component: ChessWinsGuideComponent },
  { path: 'guides/multi-day-rewards', component: MultiDayRewardsGuideComponent },
  { path: 'guides/trading', component: TradingGuideComponent },
  { path: 'guides/path-season', component: PathSeasonGuideComponent },
  { path: 'guides/mystic-skill-materials', component: MysticSkillMaterialsGuideComponent },
  { path: 'guides/mystic-metrics', component: MysticMetricsGuideComponent },
  { path: 'tools', component: ToolsHubComponent },
  { path: 'tools/chinese-chess', component: ChineseChessComponent },
  { path: 'tools/mystic-upgrade-planner', component: MysticUpgradePlannerComponent },
  { path: 'tools/settings', component: SettingsIoComponent },
  { path: 'privacy', component: PrivacyComponent },
  { path: '**', redirectTo: 'home' },
];
