import { ChecklistItem } from '../models';

export const SEASONAL_WEEKLY_CHECKLIST: ChecklistItem[] = [
  {
    id: 'bp-weekly-exploration-500',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Obtain 500 Exploration.',
    description:
      'Earn a total of 500 Exploration points across the world during the week for Battle Pass EXP.',
    tags: ['exploration', 'solo'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-clear-heros-realm',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Clear Hero’s Realm once.',
    description: 'Complete one run of Hero’s Realm this week.',
    tags: ['combat', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-sword-trial-5',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Clear Sword Trial 5 times.',
    description: 'Finish Sword Trial a total of five times in the week.',
    tags: ['combat', 'solo', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-leisure-slips-100',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Obtain 100 Adventure Slips from Leisure modes.',
    description: 'Run Leisure modes to earn at least 100 Adventure Slips during the week.',
    tags: ['leisure', 'multiplayer', 'economy'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-stamina-300',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Consume 300 Stamina.',
    description: 'Spend 300 Stamina on crafting, gathering or other Stamina sinks over the week.',
    tags: ['economy', 'progression', 'solo'],
    seasonId: 'jade-table-s1',
    expired: false,
  },

  {
    id: 'bp-weekly-jade-fish-1000',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Obtain 1,000 Jade Fish.',
    description:
      'Accumulate 1,000 Jade Fish from activities during the week to push Battle Pass progress.',
    tags: ['economy'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-sect-command-4',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Complete Sect Command 4 times.',
    description: 'Finish four Sect Command runs this week.',
    tags: ['guild', 'combat', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-energy-100',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Consume 100 Energy.',
    description: 'Spend a total of 100 Energy in any content during the week.',
    tags: ['progression', 'combat'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-treasure-tokens-500',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Obtain 500 Treasure Tokens from Guild events.',
    description: 'Take part in Guild events and earn at least 500 Treasure Tokens over the week.',
    tags: ['economy', 'guild', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-intimacy-1000',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Increase 1,000 Intimacy with other players.',
    description:
      'Play with friends/partners and use gifts or co-op content to raise Intimacy by 1,000 total.',
    tags: ['social', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },

  {
    id: 'bp-weekly-campaign-challenge-5',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Complete Campaign – Challenge 5 times.',
    description: 'Run Challenge difficulty Campaign stages five times this week.',
    tags: ['combat', 'solo', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-outpost-challenge-5',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Complete Outpost – Challenge 5 times.',
    description: 'Run Challenge difficulty Outpost stages five times this week.',
    tags: ['combat', 'solo', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-trials-5',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Complete 5 Trials.',
    description: 'Clear any combination of Trials five times this week.',
    tags: ['combat', 'solo'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-arena-2',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Complete any Arena 2 times.',
    description: 'Participate in Arena matches at least twice during the week.',
    tags: ['combat', 'multiplayer'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-weekly-heal-players-2',
    frequency: 'seasonal-weekly',
    importance: 'core',
    category: 'Battle Pass – Weekly',
    label: 'Successfully heal other players 2 times.',
    description:
      'Use healing skills or support mechanics to successfully heal allies in combat two times.',
    tags: ['combat', 'multiplayer', 'social'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
];
