import { ChecklistItem } from '../../models';

export const SEASONAL_PERIOD_CHECKLIST: ChecklistItem[] = [
  {
    id: 'bp-period-consume-energy-2200',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Consume 2,200 Energy.',
    description:
      'Spend 2,200 Energy over the course of the season; any Energy-consuming content counts.',
    tags: ['progression', 'combat'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-gone-fishing-4th-realm',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Engagement reaches Gone Fishing – 4th Realm.',
    description: 'Advance the “Gone Fishing” system to the 4th Realm before the season ends.',
    tags: ['leisure', 'progression'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-qinghe-exploration-3000',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Qinghe Exploration reaches 3,000.',
    description: 'Raise your Qinghe region Exploration score to 3,000.',
    tags: ['exploration', 'solo'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-kaifeng-exploration-3000',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Kaifeng Exploration reaches 3,000.',
    description: 'Raise your Kaifeng region Exploration score to 3,000.',
    tags: ['exploration', 'solo'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-complete-chapter-1',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Complete Chapter One: Heaven Has No Pier.',
    description: 'Finish the first main-story chapter “Heaven Has No Pier”.',
    tags: ['adventure', 'progression'],
    seasonId: 'jade-table-s1',
    expired: false,
  },

  {
    id: 'bp-period-complete-chapter-2',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Complete Chapter Two: Furnace of Heaven and Earth.',
    description: 'Finish the second main-story chapter “Furnace of Heaven and Earth”.',
    tags: ['adventure', 'progression'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-compendium-150',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Compendium Collection reaches 150.',
    description: 'Collect at least 150 entries in your Compendium by the end of the season.',
    tags: ['exploration', 'progression'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-open-90-chests',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Open 90 chests on the map.',
    description: 'Open a total of 90 world chests across all regions.',
    tags: ['exploration', 'solo'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-melodies-of-peace-15',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Activate Melodies of Peace 15 times.',
    description: 'Use the “Melodies of Peace” interaction 15 times during the season.',
    tags: ['leisure', 'social'],
    seasonId: 'jade-table-s1',
    expired: false,
  },

  {
    id: 'bp-period-level-35',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Character reaches Lv 35.',
    description: 'Level your main character to at least level 35.',
    tags: ['progression', 'stats'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-draw-50',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Draw 50 times.',
    description: 'Perform a total of 50 premium or standard draws (gacha pulls) over the season.',
    tags: ['premium', 'economy'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-activate-talents-20',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Activate Talents 20 times cumulatively.',
    description: 'Spend Talent points to activate any 20 Talents across all Talent pages.',
    tags: ['progression', 'stats'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
  {
    id: 'bp-period-online-90-min',
    frequency: 'seasonal-period',
    importance: 'core',
    category: 'Battle Pass – Season Objectives',
    label: 'Play Online Mode for 90 minutes.',
    description:
      'Stay in online mode and actively play for a cumulative 90 minutes during the season.',
    tags: ['multiplayer', 'social'],
    seasonId: 'jade-table-s1',
    expired: false,
  },
];
